### ISSUE TITLE
Открытие транзакции предполагает возможность ее отката, не увидел вызов rollback.  Кстати, чем @Transactional не угодил?

### ISSUE THREAD

**Issue by aabramkin** [Lils2013/EmployeeManager#3]
https://github.com/Lils2013/EmployeeManager/blob/3d6755c0fb9cefe0b2a1864d6b226eeda1ab840b/src/main/java/ru/tsconsulting/controllers/EmployeesController.java#L84

**Comment by ghost** [comment]
Исправлено.
